$scenarios {
	$timeunit ms
	$worktasks {
		$worktask ASW_ACS_step {
			$cycletime 100
		}
		$worktask ASW_DCS_step {
			$cycletime 100
		}
		$worktask ASW_FACS_step {
			$cycletime 100
		}
		$worktask ASW_FAS_step {
			$cycletime 100
		}
		$worktask ASW_FBGE_step {
			$cycletime 100
		}
		$worktask ASW_FOME_step {
			$cycletime 100
		}
		$worktask ASW_FSTC_step {
			$cycletime 100
		}
		$worktask ASW_IME_step {
			$cycletime 100
		}
		$worktask ASW_RACS_step {
			$cycletime 100
		}
		$worktask ASW_RAS_step {
			$cycletime 100
		}
		$worktask ASW_RBGE_step {
			$cycletime 100
		}
		$worktask ASW_ROME_step {
			$cycletime 100
		}
		$worktask ASW_RSTC_step {
			$cycletime 100
		}
		$worktask ASW_SS_step {
			$cycletime 100
		}
		$worktask ASW_SSS_step {
			$cycletime 100
		}
	}

	$scenario 1 {
		$name "初始化"
		$uuid "bdd3857a-1a66-49e2-a7f8-4ac9ea07d240"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 2 {
		$name "MAX除霜"
		$uuid "d675b861-7ddf-49a1-82d0-25a12d6b74ef"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 3 {
		$name "模式"
		$uuid "8ac82271-e1c4-4e59-8843-a6b876477c61"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 5
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 5
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 5
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 7
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 5
				VeFOME_FrtACOtltMdExp_enum = 6
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 5
				VeFOME_FrtACOtltMdExp_enum = 6
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 4 {
		$name "AUTO"
		$uuid "f948776b-d57d-425e-a0ae-e7efd6aa6bbe"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 5 {
		$name "主驾设置温度"
		$uuid "a73193bb-3e3d-4188-8faa-3a71e31f0e2d"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 25
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 6 {
		$name "主驾风量"
		$uuid "79f130f3-a304-4240-aac9-822c1a157a5c"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 4
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 4
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 7
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 7
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 7
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 7 {
		$name "A/C按键"
		$uuid "a53da67d-2112-408b-9771-9b60435c9aa7"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 7
				VeFOMM_FrtACAirOtltModeSts_enum = 5
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 7
				VeFOMM_FrtACAirOtltModeSts_enum = 5
				VeINP_ACSwtReqCkd_enum = 2
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 7
				VeFOME_FrtACOtltMdExp_enum = 5
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 7
				VeFOME_FrtACOtltMdExp_enum = 5
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 8 {
		$name "副驾设置温度"
		$uuid "34779617-b11a-40e5-8062-aa09191af5f9"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 25
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 9 {
		$name "循环"
		$uuid "35698ef7-d980-4f8b-90cf-7c409ef302f8"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 10 {
		$name "SYNC"
		$uuid "c043df69-c7ca-4f17-be59-81d1947ceabb"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 11 {
		$name "前排开关机"
		$uuid "95da6a7a-a6b8-49c8-9e50-e7db0e91ee1b"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 12 {
		$name "后排AUTO"
		$uuid "3b784f6d-9c7a-4b4b-9a36-b67c9b9cd5a2"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 13 {
		$name "后排设置温度"
		$uuid "711b2e2a-2be4-47d9-840f-3b771b32b9a2"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 22
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 14 {
		$name "后排风量"
		$uuid "a9c7720e-9f32-4811-a538-f8736db292e5"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 5
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 15 {
		$name "后排模式"
		$uuid "daa41b01-4113-449a-8132-847805ad79f3"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 3
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 16 {
		$name "后排开关机"
		$uuid "b2d78245-e15b-44f8-b946-480ed4246ba2"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}
}