$scenarios {
	$timeunit ms
	$worktasks {
		$worktask ASW_ACS_step {
			$cycletime 100
		}
		$worktask ASW_DCS_step {
			$cycletime 100
		}
		$worktask ASW_FACS_step {
			$cycletime 100
		}
		$worktask ASW_FAS_step {
			$cycletime 100
		}
		$worktask ASW_FBGE_step {
			$cycletime 100
		}
		$worktask ASW_FOME_step {
			$cycletime 100
		}
		$worktask ASW_FSTC_step {
			$cycletime 100
		}
		$worktask ASW_IME_step {
			$cycletime 100
		}
		$worktask ASW_RACS_step {
			$cycletime 100
		}
		$worktask ASW_RAS_step {
			$cycletime 100
		}
		$worktask ASW_RBGE_step {
			$cycletime 100
		}
		$worktask ASW_ROME_step {
			$cycletime 100
		}
		$worktask ASW_RSTC_step {
			$cycletime 100
		}
		$worktask ASW_SS_step {
			$cycletime 100
		}
		$worktask ASW_SSS_step {
			$cycletime 100
		}
	}

	$scenario 1 {
		$name "初始化"
		$uuid "dbdd4a11-bcdf-4c35-9dd5-bc612a58ef51"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 2 {
		$name "MAX除霜"
		$uuid "e2309568-d623-4536-a7e6-a0b2e1205367"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 3 {
		$name "模式"
		$uuid "1aa5b030-2367-4f13-bc6e-bbba57a16b8d"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 2
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 1
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 1
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 4 {
		$name "AUTO"
		$uuid "771dbac3-d651-4b0d-a28b-d0ca295b1f17"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = [1:2]
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 5 {
		$name "主驾设置温度"
		$uuid "3049fae7-d810-499a-87aa-46007761ec0c"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 25
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 6 {
		$name "主驾风量"
		$uuid "cc62ef29-59b9-4d1b-9dc9-ceb95c68ef8b"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 4
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 4
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 7 {
		$name "A/C按键"
		$uuid "95e06df2-4aeb-4810-8c03-9a700d152e73"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 2
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 9 {
		$name "副驾设置温度"
		$uuid "a0176aa4-7149-49df-918c-2d23265bf5b0"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 10 {
		$name "循环"
		$uuid "2029845c-5a00-4d1a-a48f-01b87de71c8d"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 1
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 11 {
		$name "SYNC"
		$uuid "8d7a76eb-03b8-46c7-9398-bfe3244ed98e"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 12 {
		$name "前排开关机"
		$uuid "8ca3db68-76c2-4caf-84df-7e839c77ce9f"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = [0:1]
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 13 {
		$name "后排AUTO"
		$uuid "48b6fcc6-62ae-4c90-829b-5d7f2a19d864"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 14 {
		$name "后排设置温度"
		$uuid "f7a10b8f-aaa9-4a6b-909c-17db99f5b259"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 26
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 26
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 26
			}
		}
	}

	$scenario 15 {
		$name "后排风量"
		$uuid "034651bd-5df1-47ab-9d43-6b14b66a7420"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 2
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 2
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 5
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 16 {
		$name "后排模式"
		$uuid "ba7b1464-bef8-4903-a924-562608b09a86"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 5
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 5
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 3
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 17 {
		$name "后排OFF"
		$uuid "0eb56989-d571-4edf-86f0-f6b1c2ca803d"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 1
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}
}