$scenarios {
	$timeunit ms
	$worktasks {
		$worktask ASW_ACS_step {
			$cycletime 100
		}
		$worktask ASW_DCS_step {
			$cycletime 100
		}
		$worktask ASW_FACS_step {
			$cycletime 100
		}
		$worktask ASW_FAS_step {
			$cycletime 100
		}
		$worktask ASW_FBGE_step {
			$cycletime 100
		}
		$worktask ASW_FOME_step {
			$cycletime 100
		}
		$worktask ASW_FSTC_step {
			$cycletime 100
		}
		$worktask ASW_IME_step {
			$cycletime 100
		}
		$worktask ASW_RACS_step {
			$cycletime 100
		}
		$worktask ASW_RAS_step {
			$cycletime 100
		}
		$worktask ASW_RBGE_step {
			$cycletime 100
		}
		$worktask ASW_ROME_step {
			$cycletime 100
		}
		$worktask ASW_RSTC_step {
			$cycletime 100
		}
		$worktask ASW_SS_step {
			$cycletime 100
		}
		$worktask ASW_SSS_step {
			$cycletime 100
		}
	}

	$scenario 1 {
		$name "初始化"
		$uuid "6b421d34-6f7b-402e-ab06-b31c200a9c3c"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 2 {
		$name "MAX除霜"
		$uuid "177a14ec-286d-48ba-b4d5-beb31c9ba24b"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 2
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 3 {
		$name "模式"
		$uuid "9a0a0633-8d1f-4ec0-a92a-d5edb4c5f3fc"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 1
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 2
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 1
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 1
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 4 {
		$name "AUTO"
		$uuid "b63cc4a1-556e-4709-ba92-76fbba10c8b2"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 5 {
		$name "主驾设置温度"
		$uuid "fe96a2c3-ab12-4c9e-8327-8b297cd353a0"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 25
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 6 {
		$name "主驾风量"
		$uuid "c96928c0-e3d9-47b3-a9bd-dd3867afe793"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 5
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 5
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 5
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 7 {
		$name "A/C按键"
		$uuid "34513bb3-9cc5-4cd3-b517-9e9d81d23235"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 2
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 8 {
		$name "副驾驶设置温度"
		$uuid "415fd558-d19c-49dc-97ec-d992a6a83f6c"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 25
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 9 {
		$name "循环"
		$uuid "0e610db8-636e-4443-980a-9061566dc802"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 10 {
		$name "SYNC"
		$uuid "76fade57-bcf2-4fe2-879e-2a6df0ba6436"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 11 {
		$name "前排开关机"
		$uuid "435de0d3-55dc-4058-ace1-aaf645ec2a51"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 12 {
		$name "后排AUTO"
		$uuid "07f6626a-1d8a-4e4f-8f06-03e34440d113"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 13 {
		$name "后排设置温度"
		$uuid "aab2b7dc-e719-4a92-8d7b-811754884310"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 25
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 25
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 25
			}
		}
	}

	$scenario 14 {
		$name "后排风量"
		$uuid "d2ba5a3e-35d6-409f-8fd8-87483c7d928d"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 2
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 2
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 5
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeROMM_RrACAirOtltModeSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 15 {
		$name "后排模式"
		$uuid "d3f8f883-fe75-47c2-8ce0-020d2767c69b"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 7
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 7
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 7
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 7
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 2
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 7
				VeROME_RrACOtltMdExp_enum = 1
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VeRBTM_RrACBlwrGearManuSts_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 7
				VeROME_RrACOtltMdExp_enum = 1
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 16 {
		$name "后排OFF"
		$uuid "9ad1868c-ef10-4b43-8734-4c50ac87db89"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 22
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}
}