$scenarios {
	$timeunit ms
	$worktasks {
		$worktask ASW_ACS_step {
			$cycletime 100
		}
		$worktask ASW_DCS_step {
			$cycletime 100
		}
		$worktask ASW_FACS_step {
			$cycletime 100
		}
		$worktask ASW_FAS_step {
			$cycletime 100
		}
		$worktask ASW_FBGE_step {
			$cycletime 100
		}
		$worktask ASW_FOME_step {
			$cycletime 100
		}
		$worktask ASW_FSTC_step {
			$cycletime 100
		}
		$worktask ASW_IME_step {
			$cycletime 100
		}
		$worktask ASW_RACS_step {
			$cycletime 100
		}
		$worktask ASW_RAS_step {
			$cycletime 100
		}
		$worktask ASW_RBGE_step {
			$cycletime 100
		}
		$worktask ASW_ROME_step {
			$cycletime 100
		}
		$worktask ASW_RSTC_step {
			$cycletime 100
		}
		$worktask ASW_SS_step {
			$cycletime 100
		}
		$worktask ASW_SSS_step {
			$cycletime 100
		}
	}

	$scenario 1 {
		$name "初始化"
		$uuid "a498c194-d6bf-4ec9-a415-60b93a9af0ae"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 2 {
		$name "MAX除霜"
		$uuid "827bcb0d-446b-41e3-aa8e-f3cd165ea04d"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 3 {
		$name "模式"
		$uuid "2064945b-5b95-4198-9cee-c3a12e9a3e0d"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 4
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 4
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 4
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 2
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 4
				VeFOME_FrtACOtltMdExp_enum = 1
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeFBCM_FrtACBlwrGearManuSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 4
				VeFOME_FrtACOtltMdExp_enum = 1
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 4 {
		$name "AUTO"
		$uuid "bf9f07b9-c51b-4446-9686-d22b28b410a9"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 5 {
		$name "主驾设置温度"
		$uuid "b486754d-28c1-4819-9e8f-c15cd4629fef"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 6 {
		$name "风量"
		$uuid "d37fe211-a2a1-4476-9e2c-cfd47adfa8a2"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 1
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 3
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 3
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 3
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 3
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 3
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeFOMM_FrtACAirOtltModeSts_enum = 0
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 3
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 7 {
		$name "A/C按键"
		$uuid "73387f16-93ac-4b52-aa91-f4451daf5dd3"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 1
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 8 {
		$name "副驾设置温度"
		$uuid "af58d6c3-5f78-44aa-8b79-5c6b59bbe557"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 9 {
		$name "循环不开机"
		$uuid "4c3da0a0-783a-4dea-bc40-dc93470ade36"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 3
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 10 {
		$name "SYNC"
		$uuid "1c7efa0b-7d10-44fd-9724-a9434122ee50"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 11 {
		$name "前排开关机"
		$uuid "3df11129-fdca-4820-bc3c-99ea1262b8c5"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 1
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 12 {
		$name "后排AUTO"
		$uuid "9443a43f-4b07-4297-b97c-dab7a64321eb"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 13 {
		$name "后排设置温度"
		$uuid "ee668a2d-3cce-4c13-953e-2fae7c8f84d0"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 14 {
		$name "后排风量"
		$uuid "81b2ebe1-deaa-4b12-9206-40c1e948d189"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 4
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 4
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 4
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 4
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 15 {
		$name "后排模式"
		$uuid "62ef1619-0e55-4b5d-9188-b52e10b45bea"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 3
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}

	$scenario 16 {
		$name "后排开关机"
		$uuid "300d35c2-ca61-4fd9-9e2d-5d935fc74f4c"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 23
				VfINP_RACSetTReqCkd_C = 24
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 1
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 1
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 23
				VfRSTC_RrACSetTempSts_C = 24
			}
		}
	}
}