$scenarios {
	$timeunit ms
	$worktasks {
		$worktask ASW_ACS_step {
			$cycletime 100
		}
		$worktask ASW_DCS_step {
			$cycletime 100
		}
		$worktask ASW_FACS_step {
			$cycletime 100
		}
		$worktask ASW_FAS_step {
			$cycletime 100
		}
		$worktask ASW_FBGE_step {
			$cycletime 100
		}
		$worktask ASW_FOME_step {
			$cycletime 100
		}
		$worktask ASW_FSTC_step {
			$cycletime 100
		}
		$worktask ASW_IME_step {
			$cycletime 100
		}
		$worktask ASW_RACS_step {
			$cycletime 100
		}
		$worktask ASW_RAS_step {
			$cycletime 100
		}
		$worktask ASW_RBGE_step {
			$cycletime 100
		}
		$worktask ASW_ROME_step {
			$cycletime 100
		}
		$worktask ASW_RSTC_step {
			$cycletime 100
		}
		$worktask ASW_SS_step {
			$cycletime 100
		}
		$worktask ASW_SSS_step {
			$cycletime 100
		}
	}

	$scenario 1 {
		$name "初始化"
		$uuid "c958c9d7-a2a3-4734-b074-70a55a5433c8"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 2 {
		$name "MAX除霜"
		$uuid "b0c4358a-3065-4926-9eb6-71c13560c4b6"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 2
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}
	}

	$scenario 3 {
		$name "模式"
		$uuid "96c59eec-18d9-4c20-8d88-4cf03fd13e67"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 1
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 9
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 1000 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 2
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 1
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 1
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 1
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 1
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 4 {
		$name "AUTO"
		$uuid "c40d15a5-b6fa-4ad8-a2ff-52cda74ab1b4"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 1
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 1
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 10
				VeFOME_FrtACOtltMdExp_enum = 7
				VeIME_ACInltMdExp_enum = 2
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 5 {
		$name "主驾设置温度"
		$uuid "c36efcbf-0d1e-4f91-8f82-73a132dbf93e"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 25
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 25
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 25
			}
		}
	}

	$scenario 6 {
		$name "主驾风量"
		$uuid "556ffc13-f125-40c5-9a91-4a69c334f668"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 5
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 5
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 5
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 7 {
		$name "A/C按键"
		$uuid "72111f52-cb76-4ccc-b242-b7fbf0e50e0e"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 2
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 8 {
		$name "副驾驶设置温度"
		$uuid "b068dc60-08f9-4ec2-943c-865aaf255890"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 25
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 1100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 1300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 26
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 25
				VfFSTC_FrtACRightSetTempSts_C = 25
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 9 {
		$name "循环"
		$uuid "8b6d9074-d9a4-42a3-8338-244a8ecf955a"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 2
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 1
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 10 {
		$name "SYNC"
		$uuid "fbed5311-543f-417a-b779-54d066f1cf04"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 2
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 11 {
		$name "前排OFF"
		$uuid "f81fc185-c8b7-4068-ad14-ace3dcc9cdd8"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 2
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 12 {
		$name "后排AUTO"
		$uuid "19fcf472-8eed-419d-938e-a83a83a5b246"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 1
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 1
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 10
				VeROME_RrACOtltMdExp_enum = 3
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 13 {
		$name "后排设置温度"
		$uuid "2a50379a-fb28-49d9-81fe-5df476c8aa2e"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 25
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 25
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 25
			}
		}
	}

	$scenario 14 {
		$name "后排风量"
		$uuid "b1a17ee4-ba9d-484d-87f1-bc456d4a5b6a"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 5
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 5
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 15 {
		$name "后排模式"
		$uuid "ad8acda4-ca17-4bd7-a5f2-00db3bc8e493"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 2
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 1
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 1
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}

	$scenario 16 {
		$name "后排开关机"
		$uuid "94204822-26b4-426c-8001-bcd4acf123db"

		$timestep $init {
			$call ASW_SS_initialize()
			$call ASW_RSTC_initialize()
			$call ASW_RBGE_initialize()
			$call ASW_RAS_initialize()
			$call ASW_IME_initialize()
			$call ASW_FSTC_initialize()
			$call ASW_FBGE_initialize()
			$call ASW_FAS_initialize()
			$call ASW_FACS_initialize()
			$call ASW_DCS_initialize()
			$call ASW_ACS_initialize()
			$call ASW_FOME_initialize()
			$call ASW_RACS_initialize()
			$call ASW_ROME_initialize()
			$call ASW_SSS_initialize()
		}

		$timestep 0 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 31.5
				VfINP_FACRightSetTReqCkd_C = 31.5
				VfINP_RACSetTReqCkd_C = 31.5
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 0
				VbFACS_FrtACSwSts_flg = 0
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 0
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 100 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 1
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 0
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 0
				VfFSTC_FrtACRightSetTempSts_C = 0
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 200 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 22
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 300 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 0
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 0
			}
		}

		$timestep 400 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 3
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 0
				VeROME_RrACOtltMdExp_enum = 0
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 500 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 3
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 0
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 600 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 1
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 700 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 0
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 1
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 800 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}

		$timestep 900 ms {
			$inputs {
				VeINP_ACSwtReqCkd_enum = 0
				VeINP_AirIntkModReqCkd_enum = 0
				VeINP_DefrstSwtReqCkd_enum = 0
				VeINP_FACAutoSwtReqCkd_enum = 0
				VeINP_FACBlwrGearManReqCkd_enum = 0
				VeINP_FACOutlModReqCkd_enum = 0
				VeINP_FACSwtReqCkd_enum = 0
				VeINP_RACAutoSwtReqCkd_enum = 0
				VeINP_RACBlwrGearManReqCkd_enum = 0
				VeINP_RACOutlModReqCkd_enum = 0
				VeINP_RACSwtReqCkd_enum = 2
				VeINP_SyncwtReqCkd_enum = 0
				VfINP_FACLeftSetTReqCkd_C = 0
				VfINP_FACRightSetTReqCkd_C = 0
				VfINP_RACSetTReqCkd_C = 0
			}
			$outputs {
				VbACS_ACSwSts_flg = 1
				VbDCS_DfstSwSts_flg = 1
				VbFACS_FrtACSwSts_flg = 1
				VbFAS_FrtACAUTOSwSts_flg = 0
				VbRACS_RrACSwSts_flg = 0
				VbRAS_RrACAUTOSwSts_flg = 0
				VbSS_SYNCSwSts_flg = 1
				VeFBGE_FrtACBlwrGearExp_enum = 3
				VeFOME_FrtACOtltMdExp_enum = 4
				VeIME_ACInltMdExp_enum = 0
				VeRBGE_RrACBlwrGearExp_enum = 3
				VeROME_RrACOtltMdExp_enum = 2
				VfFSTC_FrtACLeftSetTempSts_C = 22
				VfFSTC_FrtACRightSetTempSts_C = 22
				VfRSTC_RrACSetTempSts_C = 22
			}
		}
	}
}